import type { Driver, PrismaClient, User } from "@prisma/client";
import { TOKEN } from "./constants";
import { generateRefreshTokenValue, sha256 } from "./hash";
import {
  InvalidRefreshTokenError,
  RefreshTokenReuseError,
  PhoneAlreadyRegisteredError,
  UserNotFoundError,
} from "./errors";
import { signAccessToken, verifyVerificationToken } from "./tokens";

const DAY_MS = 24 * 60 * 60 * 1000;

export interface AuthTokens {
  accessToken: string;
  refreshToken: string;
}

/**
 * Signs a fresh access token and creates+stores a new refresh token row for
 * `user`.
 *
 * `familyId` links the new token into an existing rotation chain. Omit it at
 * login to start a new chain — the row is then its own family root, which is
 * why the create is followed by a self-referencing update.
 */
async function issueTokens(
  prisma: PrismaClient,
  user: Pick<User, "id" | "role">,
  now: Date = new Date(),
  familyId?: string,
): Promise<AuthTokens> {
  const accessToken = signAccessToken({ userId: user.id, role: user.role });

  const refreshToken = generateRefreshTokenValue();
  const expiresAt = new Date(now.getTime() + TOKEN.REFRESH_TOKEN_TTL_DAYS * DAY_MS);

  const created = await prisma.refreshToken.create({
    data: {
      userId: user.id,
      tokenHash: sha256(refreshToken),
      expiresAt,
      // Placeholder for a brand-new chain; replaced with the row's own id
      // immediately below, since cuid() is generated by the database layer.
      familyId: familyId ?? "",
    },
  });

  if (!familyId) {
    await prisma.refreshToken.update({
      where: { id: created.id },
      data: { familyId: created.id },
    });
  }

  return { accessToken, refreshToken };
}

export type SignupRole = "RIDER" | "DRIVER";

export interface SignupInput {
  phone: string;
  name: string;
  role: SignupRole;
  /** Verification token returned by /auth/verify-otp for purpose=SIGNUP. */
  verifiedToken: string;
}

export interface SignupResult extends AuthTokens {
  user: User & { driver: Driver | null };
}

/**
 * Creates a new User (and, for DRIVER, a pending Driver row with
 * isApproved=false and an empty profile awaiting completeDriverProfile).
 * Throws PhoneAlreadyRegisteredError if the phone is already registered.
 */
export async function signup(prisma: PrismaClient, input: SignupInput): Promise<SignupResult> {
  verifyVerificationToken(input.verifiedToken, input.phone, "SIGNUP");

  const existing = await prisma.user.findUnique({ where: { phone: input.phone } });
  if (existing) {
    throw new PhoneAlreadyRegisteredError(input.phone);
  }

  const user = await prisma.user.create({
    data: {
      phone: input.phone,
      name: input.name,
      role: input.role,
      // For DRIVER, create the pending Driver row (empty profile, isApproved=false)
      // in the same write and include it below, so the signup response carries the
      // same `user.driver` shape as /me and login. carMake stays null, so the
      // onboarding gate still correctly routes a new driver to onboarding.
      ...(input.role === "DRIVER" ? { driver: { create: { isApproved: false } } } : {}),
    },
    include: { driver: true },
  });

  const tokens = await issueTokens(prisma, user);
  return { user, ...tokens };
}

export interface LoginInput {
  phone: string;
  /** Verification token returned by /auth/verify-otp for purpose=LOGIN. */
  verifiedToken: string;
}

export interface LoginResult extends AuthTokens {
  user: User & { driver: Driver | null };
}

/** Logs in an existing user. Throws UserNotFoundError if no account exists for the phone. */
export async function login(prisma: PrismaClient, input: LoginInput): Promise<LoginResult> {
  verifyVerificationToken(input.verifiedToken, input.phone, "LOGIN");

  const user = await prisma.user.findUnique({
    where: { phone: input.phone },
    include: { driver: true },
  });
  if (!user) {
    throw new UserNotFoundError(input.phone);
  }

  const tokens = await issueTokens(prisma, user);
  return { user, ...tokens };
}

/**
 * Validates a refresh token and rotates it: the old token is revoked and a
 * new access + refresh token pair is issued, inheriting the same rotation
 * family. Unknown or expired tokens throw InvalidRefreshTokenError.
 *
 * THEFT DETECTION: refresh tokens are one-time — a successful refresh
 * revokes the token it consumed. So presenting an already-revoked token
 * means two parties hold the same token, i.e. one of them stole it, and we
 * cannot tell which is the legitimate client. The safe response is to revoke
 * the ENTIRE family (every token descended from that login) and force a full
 * re-authentication, which invalidates the attacker's copy too.
 *
 * NOTE: this makes concurrent refreshes with the same token look like theft.
 * The mobile client therefore single-flights refreshes (mobile-shared
 * auth/apiClient.ts) so simultaneous 401s share one call rather than firing
 * several with the same token.
 */
export async function refresh(
  prisma: PrismaClient,
  refreshToken: string,
  now: Date = new Date(),
): Promise<AuthTokens> {
  const tokenHash = sha256(refreshToken);

  const stored = await prisma.refreshToken.findFirst({
    where: { tokenHash },
    include: { user: true },
  });

  if (!stored) {
    throw new InvalidRefreshTokenError();
  }

  if (stored.revokedAt) {
    // Reuse of a consumed token — burn the whole chain, including whatever
    // token the other party is currently holding.
    await prisma.refreshToken.updateMany({
      where: { familyId: stored.familyId, revokedAt: null },
      data: { revokedAt: now },
    });
    throw new RefreshTokenReuseError(stored.userId);
  }

  if (stored.expiresAt < now) {
    throw new InvalidRefreshTokenError();
  }

  await prisma.refreshToken.update({
    where: { id: stored.id },
    data: { revokedAt: now },
  });

  return issueTokens(prisma, stored.user, now, stored.familyId);
}

/** Revokes a single refresh token (e.g. on logout). Throws InvalidRefreshTokenError if unknown/already revoked. */
export async function logout(
  prisma: PrismaClient,
  refreshToken: string,
  now: Date = new Date(),
): Promise<void> {
  const tokenHash = sha256(refreshToken);

  const stored = await prisma.refreshToken.findFirst({ where: { tokenHash } });
  if (!stored || stored.revokedAt) {
    throw new InvalidRefreshTokenError();
  }

  await prisma.refreshToken.update({
    where: { id: stored.id },
    data: { revokedAt: now },
  });
}

/** Revokes all of a user's active refresh tokens (e.g. on suspected compromise). */
export async function revokeAllForUser(
  prisma: PrismaClient,
  userId: string,
  now: Date = new Date(),
): Promise<void> {
  await prisma.refreshToken.updateMany({
    where: { userId, revokedAt: null },
    data: { revokedAt: now },
  });
}

export interface CompleteDriverProfileInput {
  carMake: string;
  carModel: string;
  carColor: string;
  plate: string;
  /** Optional — Cloudinary upload deferred to a future pass. */
  photoUrl?: string;
}

/** Fills in the driver profile fields created (empty) at DRIVER signup. */
export async function completeDriverProfile(
  prisma: PrismaClient,
  userId: string,
  input: CompleteDriverProfileInput,
) {
  return prisma.driver.update({
    where: { userId },
    data: {
      carMake: input.carMake,
      carModel: input.carModel,
      carColor: input.carColor,
      plate: input.plate,
      ...(input.photoUrl !== undefined ? { photoUrl: input.photoUrl } : {}),
    },
  });
}
